### ISSUE TITLE
omitting the callback function does not work with insertOrReplaceEntity

### ISSUE THREAD

**Issue by iBrooks** [ahuggins-nhs/azure-table-promise#2] opened 2020-12-02 21:16 UTC
I have had success implementing this library using `queryEntities` and omitting the callback function as the documentation requires. I have now tried to use `insertOrReplaceEntity` but I'm met with an error `Exception: ArgumentNullError: Required argument callback for function entityOperation is not defined` By my understanding I shouldn't need a callback function when using the azure-table-promise library. 

Is it possible to support `insertOrReplaceEntity`?

**Comment by ahuggins-nhs** [comment] 2020-12-03 14:51
@iBrooks The unit tests indicate that `insertOrMergeEntity` is working, so I would expect that `insertOrReplaceEntity` also works. Do you have a code sample that I can review? I'll also take a look at adding a few more methods to the test suite to expand coverage.

I'm also considering deprecating this library since Microsoft finally released a promise-based version of their table storage library, `@azure/data-tables`; the other option is to keep this as a polyfill of the old methods and switch over to the new lib as a backend. I'm not sure yet.

Unless you're completely committed to using `azure-table-promise`, I'd recommend theirs as a long-term solution.

https://www.npmjs.com/package/@azure/data-tables

**Comment by ahuggins-nhs** [comment] 2020-12-03 23:04
@iBrooke Updated tests call `insertOrReplaceEntity` just fine. If you have the version of node you're working on and a code sample, I can see if I can reproduce. I'll leave this issue open until 5 PM CST on Friday 12/4; if I don't hear back, we can always reopen.

**Closed** 2021-01-07 20:39 UTC
